" .vimrc / init.vim
" The following vim/neovim configuration works for both Vim and NeoVim
"
" " ensure vim-plug is installed and then load it
call plug#begin('~/.config/nvim/plugged')

" General {{{
	" Copy in and out of vim
	set clipboard=unnamed

	if has('mouse')
		set mouse=a
	endif
	" error bells
	set noerrorbells
	set visualbell
	set t_vb=
	set tm=500
" }}}

" Appearance {{{
    set number " show line numbers
    set wrap " turn on line wrapping
    set wrapmargin=8 " wrap lines when coming within n characters from side
    set linebreak " set soft wrapping
    set showbreak=… " show ellipsis at breaking
    set autoindent " automatically set indent of new line
    set ttyfast " faster redrawing
    set diffopt+=vertical
    set laststatus=2 " show the satus line all the time
    set so=7 " set 7 lines to the cursors - when moving vertical
    set wildmenu " enhanced command line completion
    set hidden " current buffer can be put into background
    set showcmd " show incomplete commands
    set noshowmode " don't show which mode disabled for PowerLine
    set wildmode=list:longest " complete files like a shell
    set scrolloff=3 " lines of text around cursor
    set shell=$SHELL
    set cmdheight=1 " command bar height
    set title " set terminal title
    set showmatch " show matching braces
    set mat=2 " how many tenths of a second to blink

    " Tab control
    set noexpandtab " insert tabs rather than spaces for <Tab>
    set smarttab " tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
    set tabstop=4 " the visible width of tabs
    set softtabstop=4 " edit as if the tabs are 4 characters wide
    set shiftwidth=4 " number of spaces to use for indent and unindent
    set shiftround " round indent to a multiple of 'shiftwidth'

    " Fix backspace indent
    set backspace=indent,eol,start
    
    " code folding settings
    set foldmethod=syntax " fold based on indent
    set foldlevelstart=99
    set foldnestmax=10 " deepest fold is 10 levels
    set nofoldenable " don't fold by default
    set foldlevel=1

    " toggle invisible characters
    set list
    set listchars=tab:→\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
    set showbreak=↪

    set t_Co=256 " Explicitly tell vim that the terminal supports 256 colors
    " switch cursor to line when in insert mode, and block when not
    set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
    \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
    \,sm:block-blinkwait175-blinkoff150-blinkon175

    if &term =~ '256color'
        " disable background color erase
        set t_ut=
    endif

    " enable 24 bit color support if supported
    if (has("termguicolors"))
        set termguicolors
    endif

    " highlight conflicts
    match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'

    " Load colorschemes
    Plug 'chriskempson/base16-vim'
    Plug 'joshdick/onedark.vim'
     " LightLine {{{
        Plug 'itchyny/lightline.vim'
        Plug 'nicknisi/vim-base16-lightline'

	let g:lightline = {
        \   'colorscheme': 'base16',
        \   'active': {
        \       'left': [ [ 'mode', 'paste' ],
        \               [ 'gitbranch' ],
        \               [ 'readonly', 'filetype', 'filename' ]],
        \       'right': [ [ 'percent' ], [ 'lineinfo' ],
        \               [ 'fileformat', 'fileencoding' ],
        \               [ 'linter_errors', 'linter_warnings' ]]
        \   },
        \   'component_expand': {
        \       'linter': 'LightlineLinter',
        \       'linter_warnings': 'LightlineLinterWarnings',
        \       'linter_errors': 'LightlineLinterErrors',
        \       'linter_ok': 'LightlineLinterOk'
        \   },
        \   'component_type': {
        \       'readonly': 'error',
        \       'linter_warnings': 'warning',
        \       'linter_errors': 'error'
        \   },
        \   'component_function': {
        \       'fileencoding': 'LightlineFileEncoding',
        \       'filename': 'LightlineFileName',
        \       'fileformat': 'LightlineFileFormat',
        \       'filetype': 'LightlineFileType',
        \       'gitbranch': 'LightlineGitBranch'
        \   },
        \   'tabline': {
        \       'left': [ [ 'tabs' ] ],
        \       'right': [ [ 'close' ] ]
        \   },
        \   'tab': {
        \       'active': [ 'filename', 'modified' ],
        \       'inactive': [ 'filename', 'modified' ],
        \   },
        \   'separator': { 'left': '', 'right': '' },
        \   'subseparator': { 'left': '', 'right': '' }
        \ }
        " \   'separator': { 'left': '▓▒░', 'right': '░▒▓' },
        " \   'subseparator': { 'left': '▒', 'right': '░' }

        function! LightlineFileName() abort
            let filename = winwidth(0) > 70 ? expand('%') : expand('%:t')
            if filename =~ 'NERD_tree'
                return ''
            endif
            let modified = &modified ? ' +' : ''
            return fnamemodify(filename, ":~:.") . modified
        endfunction

        function! LightlineFileEncoding()
            " only show the file encoding if it's not 'utf-8'
            return &fileencoding == 'utf-8' ? '' : &fileencoding
        endfunction

        function! LightlineFileFormat()
            " only show the file format if it's not 'unix'
            let format = &fileformat == 'unix' ? '' : &fileformat
            return winwidth(0) > 70 ? format : '' 
            " return winwidth(0) > 70 ? format . ' ' . WebDevIconsGetFileFormatSymbol() : ''
        endfunction

        function! LightlineFileType()
            return ''
            " return WebDevIconsGetFileTypeSymbol()
        endfunction

        function! LightlineLinter() abort
            let l:counts = ale#statusline#Count(bufnr(''))
            return l:counts.total == 0 ? '' : printf('×%d', l:counts.total)
        endfunction

        function! LightlineLinterWarnings() abort
            let l:counts = ale#statusline#Count(bufnr(''))
            let l:all_errors = l:counts.error + l:counts.style_error
            let l:all_non_errors = l:counts.total - l:all_errors
            return l:counts.total == 0 ? '' : '⚠ ' . printf('%d', all_non_errors)
        endfunction

        function! LightlineLinterErrors() abort
            let l:counts = ale#statusline#Count(bufnr(''))
            let l:all_errors = l:counts.error + l:counts.style_error
            return l:counts.total == 0 ? '' : '✖ ' . printf('%d', all_errors)
        endfunction

        function! LightlineLinterOk() abort
            let l:counts = ale#statusline#Count(bufnr(''))
            return l:counts.total == 0 ? 'OK' : ''
        endfunction

        function! LightlineGitBranch()
            return "\uE725" . (exists('*fugitive#head') ? fugitive#head() : '')
        endfunction

        function! LightlineUpdate()
            if g:goyo_entered == 0
                " do not update lightline if in Goyo mode
                call lightline#update()
            endif
        endfunction

        augroup alestatus
            autocmd User ALELint call LightlineUpdate()
        augroup end
    " }}}
" }}}

" General Mappings {{{
    " set a map leader for more key combos
    let mapleader = ','
    
    "" no one is really happy until you have this shortcuts
	cnoreabbrev W! w!
	cnoreabbrev Q! q!
	cnoreabbrev Qall! qall!
	cnoreabbrev Wq wq
	cnoreabbrev Wa wa
	cnoreabbrev wQ wq
	cnoreabbrev WQ wq
	cnoreabbrev W w
	cnoreabbrev Q q
	cnoreabbrev Qall qall

    " remap esc
    inoremap jk <esc>

    " shortcut to save
    nmap <leader>, :w<cr>

    " set paste toggle
    set pastetoggle=<leader>v

    " clear highlighted search
    noremap <space> :set hlsearch! hlsearch?<cr>

    "" Clean search (highlight)
    nnoremap <silent> <leader><space> :noh<cr>

    " remove extra whitespace
    " nmap <leader><space> :%s/\s\+$<cr>
    " nmap <leader><space><space> :%s/\n\{2,}/\r\r/g<cr>
    
    "" Buffer nav
    noremap <leader>z :bp<CR>
    noremap <leader>x :bn<CR>

    " switch between current and last buffer
    nmap <leader>. <c-^>
    
    "" Close buffer
    noremap <leader>c :bd<CR>

    " enable . command in visual mode
    vnoremap . :normal .<cr>

    "" Split
    noremap <Leader>h :<C-u>split<CR>
    noremap <Leader>v :<C-u>vsplit<CR>
    
    map <silent> <C-n> :call functions#WinMove('h')<cr>
    map <silent> <C-e> :call functions#WinMove('j')<cr>
    map <silent> <C-u> :call functions#WinMove('k')<cr>
    map <silent> <C-i> :call functions#WinMove('l')<cr>

    map <leader>wc :wincmd q<cr>

    " moving up and down work as you would expect
    " nnoremap <silent> j gj
    " nnoremap <silent> k gk
    " nnoremap <silent> ^ g^
    " nnoremap <silent> $ g$

    "" Set working directory
    " nnoremap <leader>. :lcd %:p:h<CR>

    "" Opens an edit command with the path of the currently edited file filled in
    noremap <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

    "" Opens a tab edit command with the path of the currently edited file filled
    noremap <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>

    " helpers for dealing with other people's code
    nmap \t :set ts=4 sts=4 sw=4 noet<cr>
    nmap \s :set ts=4 sts=4 sw=4 et<cr>    
" }}}


" General Functionality {{{
    " insert or delete brackets, parens, quotes in pair
    Plug 'jiangmiao/auto-pairs'

    " easy commenting motions
    Plug 'tpope/vim-commentary'

    " add end, endif, etc. automatically
    Plug 'tpope/vim-endwise'

    " detect indent style (tabs vs. spaces)
    Plug 'tpope/vim-sleuth'

    " context-aware pasting
    Plug 'sickill/vim-pasta'

    " Syntax Highlighting {{{
    	Plug 'scrooloose/syntastic'
	let g:syntastic_always_populate_loc_list=1
	let g:syntastic_error_symbol='✗'
	let g:syntastic_warning_symbol='⚠'
	let g:syntastic_style_error_symbol = '✗'
	let g:syntastic_style_warning_symbol = '⚠'
	let g:syntastic_auto_loc_list=1
	let g:syntastic_aggregate_errors = 1
    " }}}

    " NERDTree {{{
        Plug 'scrooloose/nerdtree', { 'on': ['NERDTreeToggle', 'NERDTreeFind'] }
        Plug 'Xuyuanp/nerdtree-git-plugin'
        Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
        let NERDTreeDirArrowExpandable = "\u00a0" " make arrows invisible
        let NERDTreeDirArrowCollapsible = "\u00a0" " make arrows invisible

        augroup nerdtree
            autocmd!
            autocmd FileType nerdtree setlocal nolist " turn off whitespace characters
            autocmd FileType nerdtree setlocal nocursorline " turn off line highlighting for performance
        augroup END

        " Toggle NERDTree
        function! ToggleNerdTree()
            if @% != "" && @% !~ "Startify" && (!exists("g:NERDTree") || (g:NERDTree.ExistsForTab() && !g:NERDTree.IsOpen()))
                :NERDTreeFind
            else
                :NERDTreeToggle
            endif
        endfunction
        " toggle nerd tree
        nmap <silent> <leader>k :call ToggleNerdTree()<cr>
        " find the current file in nerdtree without needing to reload the drawer
        nmap <silent> <leader>y :NERDTreeFind<cr>

        let NERDTreeShowHidden=1
        " let NERDTreeDirArrowExpandable = '▷'
        " let NERDTreeDirArrowCollapsible = '▼'
        let g:NERDTreeIndicatorMapCustom = {
        \ "Modified"  : "✹",
        \ "Staged"    : "✚",
        \ "Untracked" : "✭",
        \ "Renamed"   : "➜",
        \ "Unmerged"  : "═",
        \ "Deleted"   : "✖",
        \ "Dirty"     : "✗",
        \ "Clean"     : "✔︎",
        \ 'Ignored'   : '☒',
        \ "Unknown"   : "?"
        \ }
    " }}}

    " FZF {{{
        Plug '/usr/local/opt/fzf'
        Plug 'junegunn/fzf.vim'
        
	let g:fzf_layout = { 'down': '~25%' }
       	set wildmode=list:longest,list:full
	set wildignore+=*.o,*.obj,.git,*.rbc,*.pyc,__pycache__
	let $FZF_DEFAULT_COMMAND =  "find * -path '*/\.*' -prune -o -path 'node_modules/**' -prune -o -path 'target/**' -prune -o -path 'dist/**' -prune -o  -type f -print -o -type l -print 2> /dev/null"

        if isdirectory(".git")
            " if in a git project, use :GFiles
            nmap <silent> <leader>t :GitFiles --cached --others --exclude-standard<cr>
        else
            " otherwise, use :FZF
            nmap <silent> <leader>t :FZF<cr>
        endif

        nmap <silent> <leader>s :GFiles?<cr>

        nmap <silent> <leader>r :Buffers<cr>
        nmap <silent> <leader>e :FZF<cr>
        nmap <leader><tab> <plug>(fzf-maps-n)
        xmap <leader><tab> <plug>(fzf-maps-x)
        omap <leader><tab> <plug>(fzf-maps-o)

        " Insert mode completion
        imap <c-x><c-k> <plug>(fzf-complete-word)
        imap <c-x><c-f> <plug>(fzf-complete-path)
        imap <c-x><c-j> <plug>(fzf-complete-file-ag)
        imap <c-x><c-l> <plug>(fzf-complete-line)

        nnoremap <silent> <Leader>C :call fzf#run({
        \   'source':
        \     map(split(globpath(&rtp, "colors/*.vim"), "\n"),
        \         "substitute(fnamemodify(v:val, ':t'), '\\..\\{-}$', '', '')"),
        \   'sink':    'colo',
        \   'options': '+m',
        \   'left':    30
        \ })<CR>

        command! FZFMru call fzf#run({
        \  'source':  v:oldfiles,
        \  'sink':    'e',
        \  'options': '-m -x +s',
        \  'down':    '40%'})

        command! -bang -nargs=* Find call fzf#vim#grep(
            \ 'rg --column --line-number --no-heading --follow --color=always '.<q-args>, 1,
            \ <bang>0 ? fzf#vim#with_preview('up:60%') : fzf#vim#with_preview('right:50%:hidden', '?'), <bang>0)
        command! -bang -nargs=? -complete=dir Files
            \ call fzf#vim#files(<q-args>, fzf#vim#with_preview('right:50%', '?'), <bang>0)
        command! -bang -nargs=? -complete=dir GitFiles
            \ call fzf#vim#gitfiles(<q-args>, fzf#vim#with_preview('right:50%', '?'), <bang>0)
    " }}}

    " signify {{{
        " Plug 'airblade/vim-gitgutter'
        Plug 'mhinz/vim-signify'
        let g:signify_vcs_list = [ 'git' ]
        let g:signify_sign_add               = '+'
        let g:signify_sign_delete            = '_'
        let g:signify_sign_delete_first_line = '‾'
        let g:signify_sign_change = '!'
    " }}}

    " vim-fugitive {{{
        Plug 'tpope/vim-fugitive'
        Plug 'junegunn/gv.vim'
        Plug 'sodapopcan/vim-twiggy'
        Plug 'christoomey/vim-conflicted'

        nmap <silent> <leader>gs :Gstatus<cr>
        nmap <silent> <leader>gc :Gcommit<cr>
        nmap <silent> <leader>gsh :Gpush<cr>
        nmap <silent> <leader>gll :Gpull<cr>
        nmap <leader>ge :Gedit<cr>
        nmap <silent><leader>gr :Gread<cr>
        nmap <silent><leader>gb :Gblame<cr>
        nmap <silent><leader>gd :Gvdiff<cr>
        nmap <silent><leader>gr :Gremove<cr>

    " }}}

    " ALE {{{
        Plug 'w0rp/ale' " Asynchonous linting engine
        let g:ale_set_highlights = 0
        let g:ale_change_sign_column_color = 0
        let g:ale_sign_column_always = 1
        let g:ale_sign_error = '✖'
        let g:ale_sign_warning = '⚠'
        let g:ale_echo_msg_error_str = '✖'
        let g:ale_echo_msg_warning_str = '⚠'
        let g:ale_echo_msg_format = '%severity% %s% [%linter%% code%]'

        let g:ale_linters = {
        \   'javascript': ['eslint', 'tsserver'],
        \   'typescript': ['tsserver', 'tslint'],
        \   'html': []
        \}
        let g:ale_fixers = {}
        let g:ale_fixers['javascript'] = ['prettier']
        let g:ale_fixers['typescript'] = ['prettier', 'tslint']
        let g:ale_fixers['json'] = ['prettier']
        let g:ale_fixers['css'] = ['prettier']
        let g:ale_javascript_prettier_use_local_config = 1
   	let g:ale_fix_on_save = 0
    " }}}

    " UltiSnips {{{
        Plug 'SirVer/ultisnips' " Snippets plugin
        let g:UltiSnipsExpandTrigger="<tab>"
	let g:UltiSnipsJumpForwardTrigger="<tab>"
	let g:UltiSnipsJumpBackwardTrigger="<c-b>"
	let g:UltiSnipsEditSplit="vertical"
    " }}}
    
    " Completion {{{
        if (has('nvim'))
            Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
        else
            Plug 'Shougo/deoplete.nvim'
            Plug 'roxma/nvim-yarp'
            Plug 'roxma/vim-hug-neovim-rpc'
        endif
        let g:deoplete#enable_at_startup = 1
    " }}}

" }}}
" Language-Specific Configuration {{{
    
    " html / templates {{{
        " emmet support for vim - easily create markdup wth CSS-like syntax
        Plug 'mattn/emmet-vim', { 'for': ['html', 'javascript.jsx']}
        let g:user_emmet_settings = {
        \  'javascript.jsx': {
        \      'extends': 'jsx',
        \  },
        \}

        " match tags in html, similar to paren support
        Plug 'gregsexton/MatchTag', { 'for': 'html' }

        " html5 support
        Plug 'othree/html5.vim', { 'for': 'html' }

        " mustache support
        Plug 'mustache/vim-mustache-handlebars'

        " pug / jade support
        Plug 'digitaltoad/vim-pug', { 'for': ['jade', 'pug'] }
    " }}}

    " JavaScript {{{
        Plug 'othree/yajs.vim', { 'for': [ 'javascript', 'javascript.jsx', 'html' ] }
        " Plug 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.jsx', 'html'] }
        Plug 'moll/vim-node', { 'for': 'javascript' }
        Plug 'mxw/vim-jsx', { 'for': ['javascript.jsx', 'javascript'] }
        Plug 'ternjs/tern_for_vim', { 'for': ['javascript', 'javascript.jsx'], 'do': 'npm install' }
    " }}}

    " TypeScript {{{
        Plug 'leafgarland/typescript-vim', { 'for': 'typescript' }
        Plug 'Shougo/vimproc.vim', { 'do': 'make' }

        Plug 'mhartington/nvim-typescript', { 'for': 'typescript', 'do': './install.sh' }
        let g:nvim_typescript#diagnostics_enable = 0
        let g:nvim_typescript#max_completion_detail=100
    " }}}


    " Styles {{{
        Plug 'wavded/vim-stylus', { 'for': ['stylus', 'markdown'] }
        Plug 'groenewege/vim-less', { 'for': 'less' }
        Plug 'hail2u/vim-css3-syntax', { 'for': 'css' }
        Plug 'cakebaker/scss-syntax.vim', { 'for': 'scss' }
        Plug 'gko/vim-coloresque'
        Plug 'stephenway/postcss.vim', { 'for': 'css' }
    " }}}

    " markdown {{{
        Plug 'tpope/vim-markdown', { 'for': 'markdown' }

        " Open markdown files in Marked.app - mapped to <leader>m
        Plug 'itspriddle/vim-marked', { 'for': 'markdown', 'on': 'MarkedOpen' }
        nmap <leader>m :MarkedOpen!<cr>
        nmap <leader>mq :MarkedQuit<cr>
        nmap <leader>* *<c-o>:%s///gn<cr>
    " }}}

    " JSON {{{
        Plug 'elzr/vim-json', { 'for': 'json' }
        let g:vim_json_syntax_conceal = 0
    " }}}

    " ruby
	Plug 'tpope/vim-rails'
	Plug 'tpope/vim-rake'
	Plug 'tpope/vim-projectionist'
	Plug 'thoughtbot/vim-rspec'
	Plug 'ecomba/vim-ruby-refactoring'

    " Golang {{{
    	Plug 'fatih/vim-go', { 'for': 'go', 'do': ':GoInstallBinaries' }
   	" run :GoBuild or :GoTestCompile based on the go file
	function! s:build_go_files()
	  let l:file = expand('%')
	  if l:file =~# '^\f\+_test\.go$'
	    call go#test#Test(0, 1)
	  elseif l:file =~# '^\f\+\.go$'
	    call go#cmd#Build(0)
	  endif
	endfunction

	let g:go_list_type = "quickfix"
	let g:go_fmt_command = "goimports"
	let g:go_fmt_fail_silently = 1
	let g:syntastic_go_checkers = ['golint', 'govet']
	let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }

	let g:go_highlight_types = 1
	let g:go_highlight_fields = 1
	let g:go_highlight_functions = 1
	let g:go_highlight_methods = 1
	let g:go_highlight_operators = 1
	let g:go_highlight_build_constraints = 1
	let g:go_highlight_structs = 1
	let g:go_highlight_generate_tags = 1
	let g:go_highlight_space_tab_error = 0
	let g:go_highlight_array_whitespace_error = 0
	let g:go_highlight_trailing_whitespace_error = 0
	let g:go_highlight_extra_types = 1

	autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4 softtabstop=4

	augroup completion_preview_close
	  autocmd!
	  if v:version > 703 || v:version == 703 && has('patch598')
	    autocmd CompleteDone * if !&previewwindow && &completeopt =~ 'preview' | silent! pclose | endif
	  endif
	augroup END

	augroup go

	  au!
	  au Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
	  au Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
	  au Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
	  au Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')

	  au FileType go nmap <Leader>dd <Plug>(go-def-vertical)
	  au FileType go nmap <Leader>dv <Plug>(go-doc-vertical)
	  au FileType go nmap <Leader>db <Plug>(go-doc-browser)

	  au FileType go nmap <leader>r  <Plug>(go-run)
	  au FileType go nmap <leader>t  <Plug>(go-test)
	  au FileType go nmap <Leader>gt <Plug>(go-coverage-toggle)
	  au FileType go nmap <Leader>i <Plug>(go-info)
	  au FileType go nmap <silent> <Leader>l <Plug>(go-metalinter)
	  au FileType go nmap <C-g> :GoDecls<cr>
	  au FileType go nmap <leader>dr :GoDeclsDir<cr>
	  au FileType go imap <C-g> <esc>:<C-u>GoDecls<cr>
	  au FileType go imap <leader>dr <esc>:<C-u>GoDeclsDir<cr>
	  au FileType go nmap <leader>rb :<C-u>call <SID>build_go_files()<CR>

	augroup END
 
    " }}}
    
    Plug 'ekalinin/Dockerfile.vim'

" }}}
" Language-Specific Configuration {{{
call plug#end()

" Colorscheme and final setup {{{
    " This call must happen after the plug#end() call to ensure
    " that the colorschemes have been loaded
    if filereadable(expand("~/.vimrc_background"))
        let base16colorspace=256
        source ~/.vimrc_background
    else
        let g:onedark_termcolors=16
        let g:onedark_terminal_italics=1
        colorscheme onedark
    endif
    syntax on
    filetype plugin indent on
" }}}
