" .vimrc / init.vim
" The following vim/neovim configuration works for both Vim and NeoVim


" General {{{
	" Copy in and out of vim
	set clipboard=unnamed

	if has('mouse')
		set mouse=a
	endif
	" error bells
	set noerrorbells
	set visualbell
	set t_vb=
	set tm=500
	
	" make search case insensitive unless camel case is detected
	set ignorecase
	set smartcase

	" make vim's base directory match the one of the file being edited
	" set autochdir
" }}}

" Appearance {{{
    set number " show line numbers
    set wrap " turn on line wrapping
    set wrapmargin=8 " wrap lines when coming within n characters from side
    set linebreak " set soft wrapping
    set showbreak=… " show ellipsis at breaking
    set autoindent " automatically set indent of new line
    set ttyfast " faster redrawing
    set diffopt+=vertical
    set laststatus=2 " show the satus line all the time
    set so=7 " set 7 lines to the cursors - when moving vertical
    set wildmenu " enhanced command line completion
    set hidden " current buffer can be put into background
    set showcmd " show incomplete commands
    set noshowmode " don't show which mode disabled for PowerLine
    set wildmode=list:longest " complete files like a shell
    set scrolloff=3 " lines of text around cursor
    set shell=$SHELL
    set cmdheight=1 " command bar height
    set title " set terminal title
    set showmatch " show matching braces
    set mat=2 " how many tenths of a second to blink

    " Tab control
    set noexpandtab " insert tabs rather than spaces for <Tab>
    set smarttab " tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
    set tabstop=4 " the visible width of tabs
    set softtabstop=4 " edit as if the tabs are 4 characters wide
    set shiftwidth=4 " number of spaces to use for indent and unindent
    set shiftround " round indent to a multiple of 'shiftwidth'

    " Fix backspace indent
    set backspace=indent,eol,start
    
    " code folding settings
    set foldmethod=syntax " fold based on indent
    set foldlevelstart=99
    set foldnestmax=10 " deepest fold is 10 levels
    set nofoldenable " don't fold by default
    set foldlevel=1

    " toggle invisible characters
    set list
    set listchars=tab:→\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
    set showbreak=↪

    set t_Co=256 " Explicitly tell vim that the terminal supports 256 colors
    " switch cursor to line when in insert mode, and block when not
    set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
    \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
    \,sm:block-blinkwait175-blinkoff150-blinkon175


    " highlight conflicts
    match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'
" }}}

" General Mappings {{{
" set a map leader for more key combos
let mapleader = ','

" The Tab key is mapped to Escape. Press Shift-Tab to insert a Tab.
" To minimize Tab use, you can use '<', '>' and ':set autoindent'
nnoremap <silent> <Tab> <Esc>:nohlsearch<bar>pclose<CR>
    vnoremap <Tab> <Esc><Nul> 
    inoremap <Tab> <Esc>
    nnoremap <S-Tab> i<Tab><Esc><Right>
    vnoremap <S-Tab> >gv
    inoremap <S-Tab> <Tab>

    " no one is really happy until you have this shortcuts
    cnoreabbrev W! w!
    cnoreabbrev Q! q!
    cnoreabbrev Qall! qall!
    cnoreabbrev Wq wq
    cnoreabbrev Wa wa
    cnoreabbrev wQ wq
    cnoreabbrev WQ wq
    cnoreabbrev W w
    cnoreabbrev Q q
    cnoreabbrev Qall qall

    " shortcut to save
    nmap <leader>, :w<cr>

    " set paste toggle
    set pastetoggle=<leader>v

    " clear highlighted search
    noremap <space> :set hlsearch! hlsearch?<cr>

    "" Clean search (highlight)
    nnoremap <silent> <leader><space> :noh<cr>

    " remove extra whitespace
    " nmap <leader><space> :%s/\s\+$<cr>
    " nmap <leader><space><space> :%s/\n\{2,}/\r\r/g<cr>
    
    "" Buffer nav
    noremap <leader>z :bp<CR>
    noremap <leader>x :bn<CR>

    " switch between current and last buffer
    nmap <leader>. <c-^>
    
    "" Close buffer
    noremap <leader>c :bd<CR>

    " enable . command in visual mode
    vnoremap . :normal .<cr>

    "" Split
    noremap <Leader>h :<C-u>split<CR>
    noremap <Leader>v :<C-u>vsplit<CR>
    
    map <silent> <leader><left> :call functions#WinMove('h')<cr>
    map <silent> <leader><down> :call functions#WinMove('j')<cr>
    map <silent> <leader><up> :call functions#WinMove('k')<cr>
    map <silent> <leader><right> :call functions#WinMove('l')<cr>

    map <leader>wc :wincmd q<cr>

    " NOTE : Trying out autochdir
    "" Set working directory
    " nnoremap <leader>. :lcd %:p:h<CR>
	
    "  Opens an edit command with the path of the currently edited file filled in
    " noremap <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

    " Opens a tab edit command with the path of the currently edited file filled
    " noremap <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>
" }}}

" " ensure vim-plug is installed and then load it
call plug#begin('~/.config/nvim/plugged')

    " Load colorschemes
    Plug 'marciomazza/vim-brogrammer-theme'
    " LightLine {{{
	Plug 'itchyny/lightline.vim'
    " }}}

    " General Functionality {{{
	"insert or delete brackets, parens, quotes in pair
	Plug 'tpope/vim-obsession'

	" insert or delete brackets, parens, quotes in pair
	Plug 'jiangmiao/auto-pairs'

	" easy commenting motions
	Plug 'tpope/vim-commentary'

	" add end, endif, etc. automatically
	Plug 'tpope/vim-endwise'

	" detect indent style (tabs vs. spaces)
	Plug 'tpope/vim-sleuth'

	" add/edit surrounding tags or characters
	Plug 'tpope/vim-surround'

	" context-aware pasting
	Plug 'sickill/vim-pasta'

" }}}
" Language-Specific Configuration {{{
    
    " Golang {{{
    	Plug 'fatih/vim-go', { 'for': 'go', 'do': ':GoInstallBinaries' }
   	" run :GoBuild or :GoTestCompile based on the go file
	function! s:build_go_files()
	  let l:file = expand('%')
	  if l:file =~# '^\f\+_test\.go$'
	    call go#test#Test(0, 1)
	  elseif l:file =~# '^\f\+\.go$'
	    call go#cmd#Build(0)
	  endif
	endfunction

	let g:go_list_type = "quickfix"
	let g:go_fmt_command = "goimports"
	let g:go_fmt_fail_silently = 1
	let g:syntastic_go_checkers = ['golint', 'govet']
	let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }

	let g:go_highlight_types = 1
	let g:go_highlight_fields = 1
	let g:go_highlight_functions = 1
	let g:go_highlight_methods = 1
	let g:go_highlight_operators = 1
	let g:go_highlight_build_constraints = 1
	let g:go_highlight_structs = 1
	let g:go_highlight_generate_tags = 1
	let g:go_highlight_space_tab_error = 0
	let g:go_highlight_array_whitespace_error = 0
	let g:go_highlight_trailing_whitespace_error = 0
	let g:go_highlight_extra_types = 1

	autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4 softtabstop=4

	augroup completion_preview_close
	  autocmd!
	  if v:version > 703 || v:version == 703 && has('patch598')
	    autocmd CompleteDone * if !&previewwindow && &completeopt =~ 'preview' | silent! pclose | endif
	  endif
	augroup END

	augroup go

	  au!
	  au Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
	  au Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
	  au Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
	  au Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')

	  au FileType go nmap <Leader>dd <Plug>(go-def-vertical)
	  au FileType go nmap <Leader>dv <Plug>(go-doc-vertical)
	  au FileType go nmap <Leader>db <Plug>(go-doc-browser)

	  au FileType go nmap <leader>r  <Plug>(go-run)
	  au FileType go nmap <leader>t  <Plug>(go-test)
	  au FileType go nmap <Leader>gt <Plug>(go-coverage-toggle)
	  au FileType go nmap <Leader>i <Plug>(go-info)
	  au FileType go nmap <silent> <Leader>l <Plug>(go-metalinter)
	  au FileType go nmap <C-g> :GoDecls<cr>
	  au FileType go nmap <leader>dr :GoDeclsDir<cr>
	  au FileType go imap <C-g> <esc>:<C-u>GoDecls<cr>
	  au FileType go imap <leader>dr <esc>:<C-u>GoDeclsDir<cr>
	  au FileType go nmap <leader>rb :<C-u>call <SID>build_go_files()<CR>

	augroup END
 
    " }}}

" }}}
" Language-Specific Configuration {{{
call plug#end()

" Colorscheme and final setup {{{
    " This call must happen after the plug#end() call to ensure
    " that the colorschemes have been loaded
    colorscheme brogrammer
    syntax on
    filetype plugin indent on
" }}}
