set -g default-command "login-shell"

# tmux display things in 256 colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

set -g history-limit 20000

# automatically renumber tmux windows
set -g renumber-windows on

# make window/pane index start with 1
set -g base-index 1
setw -g pane-base-index 1

unbind =
bind = select-layout tiled

# don't rename windows automatically
set-option -g allow-rename off

set-option -g set-titles on
set-option -g set-titles-string "#T - #W"

######################
#### Key Bindings ####
######################

# Use Ctrl+A as the prefix key
unbind C-b
set -g prefix `
bind ` send-prefix

# for nested tmux sessions
# bind-key ` send-prefix

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Use Vim shortcuts
setw -g mode-keys vi

# more settings to make copy-mode more vim-like
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind -Tcopy-mode-vi 'v' send -X begin-selection
bind -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "tmux save-buffer - | reattach-to-user-namespace pbcopy"

# Buffers to/from Mac clipboard, yay tmux book from pragprog
bind C-c run "tmux save-buffer - | reattach-to-user-namespace pbcopy"
bind C-v run "tmux set-buffer $(reattach-to-user-namespace pbpaste); tmux paste-buffer"

# Make `Ctrl+A R` reload the config file
unbind r
bind r source-file ~/.tmux.conf

# split panes using | and -
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# switch panes using Alt-arrow without prefix
# bind -n M-Left select-pane -L
# bind -n M-Right select-pane -R
# bind -n M-Up select-pane -U
# bind -n M-Down select-pane -D

##############################
### Color & Style Settings ###
##############################

source ~/.dotfiles/tmux/theme.sh
